
apiVersion: v2
name: platform
description: Plataforma base con ArgoCD
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: argo-cd
    version: 6.7.3        # usa la versi√≥n actual del repo
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled