argo-cd:
  server:
    extraArgs:
      - --insecure

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - argocd.jamorgado.es
      tls:
        - hosts:
            - argocd.jamorgado.es
          secretName: argocd-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
