services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/JS/react/Dockerfile
      args: #variables en DFILE para la construccion (build) de la imagen
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        
    image: morgadoberruezo/ubreact
    container_name: ctreact
    env_file:
      - .env
    ports:
      - "8810:80"
      - "3010:3000"

