jenkins:
  controller:
    # image:
    #   repository: jenkins/jenkins
    #   tag: "2.541.1-lts-jdk21"
    runAsUser: 0
    fsGroup: 0
    admin:
      username: admin
      password: admin123
    persistence:
      enabled: true
      size: 8Gi
      storageClass: microk8s-hostpath   # üëà clave
    serviceType: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: jenkins.jamorgado.es
    # CR√çTICO: Deshabilita JCasC completamente
    JCasC:
      defaultConfig: false
      configScripts: {}
    
    # CR√çTICO: Deshabilita el sidecar
    sidecars:
      configAutoReload:
        enabled: false
      installPlugins: []
      additionalPlugins: []
    installPlugins:
      - configuration-as-code:1932.v75cb_b_f1b_698d
      - kubernetes:4295.v7fa_01b_309c95
      - workflow-aggregator:600.vb_57cdd26fdd7
      - credentials:1453.v9b_a_29777a_b_fd
      - github:1.40.0
      - git:5.6.0
