services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/base/ubbase
      # args: #variables en DFILE para la construccion (build) de la imagen
        # - USUARIO=alfonso
    container_name: ${CONTENEDOR}
    # environment: # si necesito algun v.e que no est√© en la .env
    #   - USUARIO=alfonso
    #   - PASSWORD=pswalfonso
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs

