services:
  web:
    build: 
      context: /home/morgado/devops/HLC/Docker/Caronte
      dockerfile: ./dockerfiles/base/ubbase
      # args: #variables en DFILE para la construccion (build) de la imagen
        # - USUARIO=alfonso
    container_name: ctpbase
    environment:
      - USUARIO=alfonso

