services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/cibersecurity/Dockerfile
      args: #variables en DFILE para la construccion (build) de la imagen
        - PROYECTO=${PROYECTO}
        - PASSWORD=1234
    image: morgadoberruezo/ubsecurity
    container_name: ctciber
    volumes:
      - ./logs:/root/logs
    env_file:
      - .env
    ports:
      - "8810:80"
      - "3010:3000"

