apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtaller-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webtaller
  template:
    metadata:
      labels:
        app: webtaller
    spec:
      containers:
        - name: webtaller
          image: morgadoberruezo/ubjambbptaller:latest
          # imagePullPolicy: Never   # ðŸ”´ CLAVE
          ports:
            - containerPort: 80
