apiVersion: v1
kind: Pod
metadata:
  name: webtaller
spec:
  containers:
    - name: pod-webtaller
      image: morgadoberruezo/ubjambbptaller:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
