apiVersion: v1
kind: Service
metadata:
  name: webtaller-service
  namespace: proyectoTaller
spec:
  type: NodePort
  selector:
    app: webtaller
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
