services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/JS/react/Dockerfile
      args: #variables en DFILE para la construccion (build) de la imagen
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
        
    # image: ${FIRMA}/ub${INICIALES}${PROYECTO}
    image: ${FIRMA}/ub${PROYECTO}
    hostname: ${CONTENEDOR}
    container_name: ${CONTENEDOR}
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs
    ports:
      - "${PORT_WWW}:80"
      - "${PORT_NODE}:3000"

