services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/JS/react/Dockerfile
      args: #variables en DFILE para la construccion (build) de la imagen
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
    image: morgadoberruezo/autocaravaneando
    container_name: ctautocaravaneando
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs
    ports:
      - "8815:80"
      - "3015:3000"

