services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/JS/react/Dockerfile
      args: #variables en DFILE para la construccion (build) de la imagen
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
        
    image: morgadoberruezo/ubautocaravaneando
    hostname: ${HOSTNAME}
    container_name: ctreact
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs
    ports:
      - "${PORT_WWW}:80"
      - "${PORT_NODE}:3000"

